# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Roger\eric6\pyqr-draw\test.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1160, 768)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.partListBox = QtWidgets.QComboBox(self.centralWidget)
        self.partListBox.setObjectName("partListBox")
        self.horizontalLayout.addWidget(self.partListBox)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.JointButton = QtWidgets.QPushButton(self.centralWidget)
        self.JointButton.setObjectName("JointButton")
        self.gridLayout.addWidget(self.JointButton, 0, 0, 1, 1)
        self.AddButton = QtWidgets.QPushButton(self.centralWidget)
        self.AddButton.setObjectName("AddButton")
        self.gridLayout.addWidget(self.AddButton, 2, 0, 1, 1)
        self.SplitButton = QtWidgets.QPushButton(self.centralWidget)
        self.SplitButton.setObjectName("SplitButton")
        self.gridLayout.addWidget(self.SplitButton, 1, 1, 1, 1)
        self.LinkButton = QtWidgets.QPushButton(self.centralWidget)
        self.LinkButton.setObjectName("LinkButton")
        self.gridLayout.addWidget(self.LinkButton, 1, 0, 1, 1)
        self.CombineButton = QtWidgets.QPushButton(self.centralWidget)
        self.CombineButton.setObjectName("CombineButton")
        self.gridLayout.addWidget(self.CombineButton, 0, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 1, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.PropertiesButton = QtWidgets.QPushButton(self.centralWidget)
        self.PropertiesButton.setObjectName("PropertiesButton")
        self.horizontalLayout.addWidget(self.PropertiesButton)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.UndoButton = QtWidgets.QPushButton(self.centralWidget)
        self.UndoButton.setObjectName("UndoButton")
        self.horizontalLayout_2.addWidget(self.UndoButton)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_2.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_2.addWidget(self.comboBox_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.comboBox_3 = QtWidgets.QComboBox(self.centralWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.horizontalLayout_2.addWidget(self.comboBox_3)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.RunButton = QtWidgets.QPushButton(self.centralWidget)
        self.RunButton.setObjectName("RunButton")
        self.horizontalLayout_3.addWidget(self.RunButton)
        self.StopButton = QtWidgets.QPushButton(self.centralWidget)
        self.StopButton.setObjectName("StopButton")
        self.horizontalLayout_3.addWidget(self.StopButton)
        self.PinButton_11 = QtWidgets.QPushButton(self.centralWidget)
        self.PinButton_11.setObjectName("PinButton_11")
        self.horizontalLayout_3.addWidget(self.PinButton_11)
        self.horizontalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.graphics = QtWidgets.QVBoxLayout()
        self.graphics.setObjectName("graphics")
        self.verticalLayout_3.addLayout(self.graphics)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.JointButton.setText(_translate("MainWindow", "Joint"))
        self.AddButton.setText(_translate("MainWindow", "Add"))
        self.SplitButton.setText(_translate("MainWindow", "Split"))
        self.LinkButton.setText(_translate("MainWindow", "Link"))
        self.CombineButton.setText(_translate("MainWindow", "Combine"))
        self.pushButton_6.setText(_translate("MainWindow", "Lock"))
        self.PropertiesButton.setText(_translate("MainWindow", "Properties"))
        self.UndoButton.setText(_translate("MainWindow", "Undo"))
        self.checkBox.setText(_translate("MainWindow", "Drawing"))
        self.checkBox_2.setText(_translate("MainWindow", "Mechanism"))
        self.RunButton.setText(_translate("MainWindow", "Run"))
        self.StopButton.setText(_translate("MainWindow", "Stop"))
        self.PinButton_11.setText(_translate("MainWindow", "Pin"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

